### ISSUE TITLE
Replacing the model and label strings for google inception resnet v2

### ISSUE THREAD

**Issue by hannan-sultan** [natanielruiz/android-yolo#1]
Hi, 

Thanks for your good work. Can you guide me, I want to replace the default `MODEL_FILE` with inception resnet v2. It would be really helpful for me if you provide detailed answer. Thanks

**Comment by natanielruiz** [comment]
Hello,

If I am not mistaken inception-resnet is a network for image recognition or classification. This project adapts the original android tensorflow demo to the object detection task using the YOLO network. I would suggest just using the original demo and replacing the inception network with your choice network: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

To be able to do this you will have to have a serialized .pb of your trained network and replace the original network with this file. Also you will have to know the name of the input and output layer and the input size of the network. I would also try to use the stripping script provided in tensorflow on your serialized graph. You can find more info by googling all of this. Good luck.

**Comment by RiyaMaliakel** [comment]
Hi @codeloverr ,

Were you able to use your model trained on resnet in the android application for object detection(tf detect)?
