### ISSUE TITLE
Adding more labels?

### ISSUE THREAD

**Issue by EXJUSTICE** [natanielruiz/android-yolo#11]
Hello,

While looking through your code I noticed that you had defined the class labels as the YOLO v1 was trained on it. Are these all the available labels?

Looking at the source project, the same file didn't specify any labels, which made me confused as how accessing more labels would work (as in has it already been trained on more, and you're simply selectively choosing which labels to recognize)?

Thank you

**Comment by natanielruiz** [comment]
Hello,
Thank you for your comment. It has been trained on the 20 classes that I defined (Pascal VOC dataset)
Cheers
