### ISSUE TITLE
Cần you give me some articles about this implementation? Thank you

### ISSUE THREAD

**Issue by haophancs** [natanielruiz/android-yolo#18]

**Comment by haophancs** [comment]
I mean "Can you give me some articles about this implementation?". Sorry for my mistakes.

**Comment by natanielruiz** [comment]
Check this out https://medium.com/towards-data-science/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9

And then learn how to use this model with the tensorflow demo detector

**Comment by haophancs** [comment]
Thank you
