### ISSUE TITLE
To customize it for other trained model files 

### ISSUE THREAD

**Issue by abhigoku10** [natanielruiz/android-yolo#21]
@hashimshafiq @natanielruiz  Hi can u pls guide what all parameters to be changed if we change the model file trained for custom object detection. I have converted my model file using darkflow to .pb format i have to modify the current android yolo to detect other objects

**Comment by natanielruiz** [comment]
Please check the Disclaimer on the project Readme.
Cheers

**Comment by abhigoku10** [comment]
@natanielruiz  i have read the disclaimer of the project readme and its mentioned that it works only for 20 class. Can you list / suggest the steps to modify tat from 20 classes to any other classes , that would be of great help

**Comment by natanielruiz** [comment]
Hi,
I believe the Disclaimer also gives some pointers as to what code to check and change if you were to try to modify it to detect a different number of classes. Also the darkflow model should be tiny-yolo (v1). If you are able to make it more general (be able to work with different number of classes) please make a pull request and I can merge it!
Cheers!
