### ISSUE TITLE
How to use own data training model?

### ISSUE THREAD

**Issue by xieyulai** [natanielruiz/android-yolo#3]
Hi, natanielruiz.
I am using darknet to traing my own data. I only detect one class. Could guide me how to modify your code to detect only one class? Do I need to modify the parameters in `android-yolo/app/src/main/java/org/tensorflow/demo/TensorflowClassifier.java`? or anything else?
Thank you.

**Comment by natanielruiz** [comment]
Unfortunately you have to change some other things to make it work such as the c++ native code output part (the output of the model) and the TensorFlowClassifier.java (which makes sense of the c++ output). Hope this helps.
