### ISSUE TITLE
I want to add or Remove Objects?

### ISSUE THREAD

**Issue by iamharisgul** [natanielruiz/android-yolo#31]

**Comment by natanielruiz** [comment]
The app is hardcoded for 20 classes and for the tiny-yolo network final output layer. You can check the following code if you want to change this:

https://github.com/natanielruiz/android-yolo/blob/master/app/src/main/java/org/tensorflow/demo/TensorflowClassifier.java

The code describes the interpretation of the output.

The code for the network inference pass is written in C++ and the output is passed to Java. The output of the network is in the form of a String which is converted to a StringTokenizer and is then converted into an array of Floats in line 87 of TensorflowClassifier.java

You can work from there and read the papers to transform the new yolo model output into something that makes sense. (I did it only for one bounding box and also obtained the confidence of this bounding box). This part of the code is commented by me so you can understand what I did. Also read the paper here: https://arxiv.org/abs/1506.02640

**Comment by iamharisgul** [comment]
Hi Nataniel Ruiz,
Thanks for your response.your app is so useful but i want to train it
according to my needs.where is dataset in the source code like(images of
these 20 objects)? I want to reduce its size as well.
Another main point the app crashes on many android device how we can fix
it. Looking forward.thanks

Best regards Haris

On 24 Mar 2018 5:09 am, "Nataniel Ruiz" <notifications@github.com> wrote:

The app is hardcoded for 20 classes and for the tiny-yolo network final
output layer. You can check the following code if you want to change this:

https://github.com/natanielruiz/android-yolo/blob/master/app/src/main/java/
org/tensorflow/demo/TensorflowClassifier.java

The code describes the interpretation of the output.

The code for the network inference pass is written in C++ and the output is
passed to Java. The output of the network is in the form of a String which
is converted to a StringTokenizer and is then converted into an array of
Floats in line 87 of TensorflowClassifier.java

You can work from there and read the papers to transform the new yolo model
output into something that makes sense. (I did it only for one bounding box
and also obtained the confidence of this bounding box). This part of the
code is commented by me so you can understand what I did. Also read the
paper here: https://arxiv.org/abs/1506.02640

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/natanielruiz/android-yolo/issues/31#issuecomment-375829356>,
or mute the thread
