### ISSUE TITLE
crash when change android_graph.pb 

### ISSUE THREAD

**Issue by xhzzhang** [natanielruiz/android-yolo#34]
Hello, this project is very good when i test, but when I use darkflow tool to convert my weight and cfg file to new android_graph.pb, then replace old one, and change the class_labels[] in java file, then got new apk, but test got crash message as below, Is it anything wrong in my step? anybody can helo me?

...
I/native: stat_summarizer.cc:33 StatSummarizer found 349 nodes
          tensorflow_jni.cc:137 Creating session.
A/native: tensorflow_jni.cc:140 Could not create TensorFlow Graph: Not found: Op type not registered 'RealDiv'
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3109 (ImageListener)
Application terminated.

**Comment by natanielruiz** [comment]
The app is hardcoded for 20 classes (pascal voc), this is the reason.
