### ISSUE TITLE
detect multiple objects

### ISSUE THREAD

**Issue by shootingliu** [natanielruiz/android-yolo#5]
Thank you for your nice implementation.
I would like to know whether the APP can detect multiple objects at the same time,just like YOLO's demo picture dog.jpg?
Thanks~

**Comment by natanielruiz** [comment]
Hello,
This app currently only supports a single object detection (highest confidence). I might work on supporting multiple objects in the future.

If you want to do it yourself I can give you some general pointers. You need to play with the output of the c++ native code (check the YOLO paper to see how they get multiple bounding boxes), do non-maxima suppression and code the appearance of multiple bounding boxes. If you have any more questions just post them here. Cheers
